nothing

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -33,6 +33,12 @@ jobs:
         id: extract_unit_name
         run: echo "UNIT_NAME=$(git log -1 --pretty=format:'%s' | grep -oP '(?<=provision superset )\S+')" >> "$GITHUB_OUTPUT"
 
+      - name: Check commit message format
+        run: |
+          if [[ "${{ steps.extract_unit_name.outputs.unit_name }}" == "" ]]; then
+            echo "Commit message does not match the required format."
+            exit 1
+          fi
       - name: Login to GitHub Container Registry 
         uses: docker/login-action@v2
         with:
